# 应用相关
APP_NAME: "JANK_BLOG"
APP_PORT: "9010"

# 数据库相关
DB_NAME: "jank"
DB_HOST: "127.0.0.1"
DB_PORT: "3306"
DB_USER: "root"
DB_PSW: "<DATABASE_PASSWORD>"

# Redis 相关
REDIS_HOST: "127.0.0.1"
REDIS_DB: "0"
REDIS_PSW: ""

# 日志
LOG_FILE_PATH: ".logs/"
LOG_FILE_NAME: "app.log"
LOG_TIMESTAMP_FMT: "2006-01-02 15:04:05"
LOG_MAX_AGE: 72
LOG_ROTATION_TIME: 24
LOG_LEVEL: "INFO"

# Swagger 相关
SWAGGER_HOST: "localhost:9010"

# QQ 邮箱和 SMTP 授权码
QQ_SMTP: "<QQ_SMTP>"
FROM_EMAIL: "<FROM_QQ_EMAIL>"
